theme = "skgadi-w3"
languageCode = "en-us"
title = "Web-tools"

baseurl = "https://tools.skgadi.com/"
[params]
	CommonTitle = "Web tools"
	SubTitle = "Web tools designed by Suresh Kumar Gadi"
	Copyright = "2017 Suresh Kumar Gadi"
#	email = "gadisureshkumar-at-gmail-dot-com"
	ORCID = "0000-0001-7974-7825"
	GScholar = "efqOY90AAAAJ"
	GPlus = "+SureshKumarGadi"
	LinkedIn = "skgadi"
	Twitter = "SureshKumarGadi"
	Maps = "https://goo.gl/maps/8NrtjMajSUz"
#	Phone = "+52 (1) 449 182 0153"
	Fax = "+52 (1) 871 757 0153"
	Address = "Carretera Torreón - Matamoros Km. 7.5, Ciudad Universitaria, Torreón, Coahuila, México, C.P. 27276"
	GoogleAnalyticsID = "UA-89998286-2"
	Author = "Suresh Kumar Gadi"
	
[params.meta.Keywords]
	name = ["skgadi", "suresh kumar gadi", "control digital"]
[params.meta.Description]
	name = "Dr. Suresh Kumar Gadi is a research professor at the Universidad Autónoma de Coahuila"


[[menu.main]]
    identifier = "Home"
    name = "Home"
    url = "/"
	weight = 0

[[menu.main]]
    identifier = "skgadi.com"
    name = "Home page"
    url = "https://SKGadi.com"
	weight = 1
[[menu.main]]
    identifier = "Mathematics"
    name = "Mathematical tools"
    url = "/mathematics/"
	weight = 2
